version: "3"
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - PGUSER=ZJ
      - PGHOST=db
      - PGPASSWORD=articlePass
      - PGDATABASE=posts
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=posts
      - POSTGRES_USER=ZJ
      - POSTGRES_PASSWORD=articlePass
volumes:
  dbdata:
